### ISSUE TITLE
Can't use my email, why?

### ISSUE THREAD

**Issue by Fleischers** [nataliiaAndrosova/Online-Store-App#3]
Alert says 'Please input a valid email'.

But my email is a valid email!

**Comment by nataliiaAndrosova** [comment]
посмотри public/js/views/users/create  79я строка, regExp для валидации
мэйла

2016-04-30 14:24 GMT+00:00 Glib Ischenko <notifications@github.com>:

**Comment by Fleischers** [comment]
@nataliiaAndrosova Why not this regexp?
http://stackoverflow.com/questions/46155/validate-email-address-in-javascript

/cc @belrestro

**Comment by nataliiaAndrosova** [comment]
fixed

2016-04-30 16:05 GMT+00:00 Glib Ischenko <notifications@github.com>:
